#! /usr/bin/env python2

import sys
import os

DEFAULT_SOURCE_URL = 'https://github.com/EvanHahn/umpm.git'
DEFAULT_SOURCE = 'umpm'

path = {}
path['main'] = '~/.umpm'
path['sources'] = '~/.umpm/sources'
path['default_source'] = '~/.umpm/sources/' + DEFAULT_SOURCE
path['cloned_bin'] = path['default_source'] + '/umpm'
path['bin'] = '~/.umpm/bin'
path['man'] = '~/.umpm/man'
path['blue'] = '~/.umpm/blue'
for key in path:
    path[key] = os.path.expanduser(path[key])

already_installed = os.path.isdir(path['main'])
is_development = '--dev' in sys.argv

if already_installed:
    print 'umpm seems to already be installed!'
    print 'Uninstall it like so:'
    print
    print '    rm -rf ' + path['main']
    print
    print 'Try reinstalling after you do that.'
    exit(1)

if is_development:
    print 'Installing umpm in development mode...'
else:
    print 'Installing umpm...'

os.mkdir(path['main'])
os.mkdir(path['sources'])
os.mkdir(path['bin'])
os.mkdir(path['man'])
os.mkdir(path['blue'])

if '--dev' in sys.argv:
    os.system('ln -s ' + os.getcwd() + ' ' + path['default_source'])
else:
    git_command = 'git clone -q ' + DEFAULT_SOURCE_URL + ' '
    git_command += path['default_source']
    os.system(git_command)

os.system('ln -s ' + path['cloned_bin'] + ' ' + path['bin'])

print

print 'Install complete! One last step...'
print 'Make sure you add the following to the beginning of your $PATH:'
print path['bin']
