#!/bin/bash

set -e

if [ -z $CLONE_URL ]; then
  CLONE_URL="https://github.com/EvanHahn/umpm.git"
fi
UMPM_PATH="$HOME/.umpm"

if [[ -e $UMPM_PATH ]]; then
  echo "umpm seems to already be installed!" 1>&2;
  echo "You can uninstall it like this:" 1>&2;
  echo 1>&2;
  echo "    rm -rf $UMPM_PATH" 1>&2;
  echo 1>&2;
  exit 1
fi

mkdir $UMPM_PATH
mkdir $UMPM_PATH/sources
mkdir $UMPM_PATH/bin
mkdir $UMPM_PATH/lib
mkdir $UMPM_PATH/man
mkdir $UMPM_PATH/tmp

git clone -q $CLONE_URL $UMPM_PATH/sources/umpm

ln -s $UMPM_PATH/sources/umpm/umpm $UMPM_PATH/bin

echo "Install complete! One last thing..."
echo "Add the following two lines to your .bash_profile (or bashrc, or whatever):"
echo
echo "    export PATH='$UMPM_PATH/bin:\$PATH'"
echo "    export LD_LIBRARY_PATH='$UMPM_PATH/lib:\$LD_LIBRARY_PATH'"
